### ISSUE TITLE
Print System.out (legacy logs) with ErRabbit and Log4j

### ISSUE THREAD

**Issue by maurcarvalho** [soleaf/ErRabbit#17]
Hello ErRabbit team,
We are migrating our applications to use ErRabbit, especially to get an advantage of remote log viewer and report features. Congratulations, it's a great project!

Although, we found an issue when we tried to watch the old application logs, which are using System.out calls. It was almost 6k calls and migrate all of them to Log4j was not an option. 
We figured out a solution creating a wrapper class and calling it on application startup. Once it could be a common issue, we would like to share it and if accepted, increase the project documentation with these approaches.

For us, our web app starts on ServletContextListener.contextInitialized. This is where we call the wrapper class to use the Log4j equivalent methods and automatically make it visible to ErRabbit.

@soleaf Follow the code snippets for your analyses:

1 - Create the LoggerWrapper

```
import java.io.IOException;
import java.io.OutputStream;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;

public class LoggerStream extends OutputStream {

    private final Logger logger;
    private final Level logLevel;
    private final OutputStream outputStream;

    public LoggerStream(Logger logger, Level logLevel, OutputStream outputStream) {

        super();
        this.logger = logger;
        this.logLevel = logLevel;
        this.outputStream = outputStream;
    }

    @Override
    public void write(byte[] b) throws IOException {

        outputStream.write(b);
        String string = new String(b);
        if (!string.trim().isEmpty())
            logger.log(logLevel, string);
    }

    @Override
    public void write(byte[] b, int off, int len) throws IOException {

        outputStream.write(b, off, len);
        String string = new String(b, off, len);
        if (!string.trim().isEmpty())
            logger.log(logLevel, string);
    }

    @Override
    public void write(int b) throws IOException {

        outputStream.write(b);
        String string = String.valueOf((char) b);
        if (!string.trim().isEmpty())
            logger.log(logLevel, string);
    }
}

```

2 - Set System methods to use your implementation

```
import java.io.PrintStream;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;

public class SysOutToLog4jWrapper {

    public static void setOut() {
        System.setOut(new PrintStream(new LoggerStream(Logger.getLogger("out"), Level.INFO, System.out)));
    }

    public static void setErr() {
        System.setErr(new PrintStream(new LoggerStream(Logger.getLogger("err"), Level.ERROR, System.err)));
    }

}

```

3 -  Init the wrapper during application startup

```
public void contextInitialized(ServletContextEvent evt) {
      // .... 
      SysOutToLog4jWrapper. setOut();
      SysOutToLog4jWrapper. setErr();
     // .... other methods
```

Let me know if you want to increase the project documentation with it. I'll make it with pleasure.

Many thanks,
MC

**Comment by oy-ilho** [comment]
Thank you 👍 
I think this is useful information.
And this document would be inserted document.
Please give me the pull request.
:D

**Comment by maurcarvalho** [comment]
Great!

I Will update the wiki and read.me file

👍

**Comment by oy-ilho** [comment]
I added your name as author of document.
(https://github.com/soleaf/ErRabbit/wiki/Read-System.*-output-with-ErRabbit-and-Log4j)
Thank you !

**Comment by maurcarvalho** [comment]
Great! 
Thanks for the referral 👍
