### ISSUE TITLE
로그 디테일 뷰 보기

### ISSUE THREAD

**Issue by hnccho** [soleaf/ErRabbit#4]
프로그램을 잘 만들었네요.
MongoDB와 ActiveMQ를 설치해서 보는 게 힘들었지만 대강 설치해서 실행하니 화면이 잘 나옵니다.
근데 LOGS화면에서 상세로그(트레이스로그)를 보려고 하는데 아무리해도 버튼을 못찼겠네요.
어떻게 봐야 하나요?

**Comment by oy-ilho** [comment]
Exception을 포함하고 잇는 로그의 경우에는, 로그레벨 아이콘이 주황색으로 채워지고요. 로그의 메세지에 마우스를 대시면 포인터가 손가락모양이 됩니다. 이때 누르면 확인하실 수 있습니다.

Exception이 로그에 수집되기 위해 선행 되어야하는 조건은 아래의 예처럼 로그를 하실때, Exception을 두번째 arg로
로그 하시면 됩니다.

try {
  ...
} 
catch(Exception e){
   logger.error("메세지", e);
}

**Comment by hnccho** [comment]
알겠습니다. 감사합니다 다시 한번 테스트해 보겠습니다. 
------ Original Message ------
Date: Tuesday, Dec 22, 2015 06:47:48 PM

**Comment by hnccho** [comment]
에러가 주황색 라벨로 나오고 손모양의 커서로 바뀌어서 클릭하였지만 상세화면이 나오지 않고 레벨이 필터가 된 리스트 화면이 나옵니다. example은 ErRabbit-log4j2-example 프로그램을 사용하였습니다.

**Comment by oy-ilho** [comment]
레벨이나, 클래스 명이 나오는 부분 아래 회색글씨로 나오는 메세지를 부분을 클릭해 주세요.

**Comment by oy-ilho** [comment]
제가 지금 밖이라서 스크린샷을 첨부 드릴수가 없네요

**Comment by hnccho** [comment]
서버타임있는 곳을 찍으니까 보이네요. 상세보기 버튼을 별도로 만들어 놓으면 이해하기 좋을 것 같습니다. 더 테스트해보고 개선 사항있으면 알려드릴께요. ^^

**Comment by oy-ilho** [comment]
피드백 감사합니다 :D
